name: ttl_cache
description: A simple key-value store whose entires expire after a user-defined time-to-live (TTL)
repository: https://github.com/bryanoltman/ttl_cache
version: 0.3.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.1.1

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ">=5.0.0 <10.0.0"
